Fix missing compareTo(Object) method for AnrStackTrace
  Sentry.Bindings.Android net10.0-android36.0 failed with 1 error(s) (2.6s)
    /Users/jpnurmi/Projects/sentry/sentry-dotnet/src/Sentry.Bindings.Android/obj/Release/net10.0-android36.0/generated/src/IO.Sentry.Android.Core.Anr.AnrStackTrace.cs(20,74): error CS0535: 'AnrStackTrace' does not implement interface member 'IComparable.CompareTo(Object)'
  Sentry.Bindings.Android net9.0-android35.0 failed with 1 error(s) (2.3s)
    /Users/jpnurmi/Projects/sentry/sentry-dotnet/src/Sentry.Bindings.Android/obj/Release/net9.0-android35.0/generated/src/IO.Sentry.Android.Core.Anr.AnrStackTrace.cs(20,74): error CS0535: 'AnrStackTrace' does not implement interface member 'IComparable.CompareTo(Object)'