Metadata.xml: remove UpdateStatus to avoid CS0108 for conflicting _members fields in nested subclasses
  Sentry.Bindings.Android net8.0-android34.0 failed with 3 error(s) (6.9s)
    /home/jpnurmi/Projects/sentry/sentry-dotnet/src/Sentry.Bindings.Android/obj/Release/net8.0-android34.0/generated/src/Sentry.JavaSdk.UpdateStatus.cs(24,35): error CS0108: 'UpdateStatus.NewRelease._members' hides inherited member 'UpdateStatus._members'. Use the new keyword if hiding was intended.
    /home/jpnurmi/Projects/sentry/sentry-dotnet/src/Sentry.Bindings.Android/obj/Release/net8.0-android34.0/generated/src/Sentry.JavaSdk.UpdateStatus.cs(90,35): error CS0108: 'UpdateStatus.UpdateError._members' hides inherited member 'UpdateStatus._members'. Use the new keyword if hiding was intended.
    /home/jpnurmi/Projects/sentry/sentry-dotnet/src/Sentry.Bindings.Android/obj/Release/net8.0-android34.0/generated/src/Sentry.JavaSdk.UpdateStatus.cs(157,35): error CS0108: 'UpdateStatus.UpToDate._members' hides inherited member 'UpdateStatus._members'. Use the new keyword if hiding was intended.
  Sentry.Bindings.Android net9.0-android35.0 failed with 3 error(s) (7.8s)
    /home/jpnurmi/Projects/sentry/sentry-dotnet/src/Sentry.Bindings.Android/obj/Release/net9.0-android35.0/generated/src/Sentry.JavaSdk.UpdateStatus.cs(24,35): error CS0108: 'UpdateStatus.NewRelease._members' hides inherited member 'UpdateStatus._members'. Use the new keyword if hiding was intended.
    /home/jpnurmi/Projects/sentry/sentry-dotnet/src/Sentry.Bindings.Android/obj/Release/net9.0-android35.0/generated/src/Sentry.JavaSdk.UpdateStatus.cs(90,35): error CS0108: 'UpdateStatus.UpdateError._members' hides inherited member 'UpdateStatus._members'. Use the new keyword if hiding was intended.
    /home/jpnurmi/Projects/sentry/sentry-dotnet/src/Sentry.Bindings.Android/obj/Release/net9.0-android35.0/generated/src/Sentry.JavaSdk.UpdateStatus.cs(157,35): error CS0108: 'UpdateStatus.UpToDate._members' hides inherited member 'UpdateStatus._members'. Use the new keyword if hiding was intended