fix: Don't run InstallAndroidDependencies during integration tests
Hopefully fixes intermittent error installing Android SDKs when running integration tests:
```
RuntimeException: Failed to install android dependencies.
  at <ScriptBlock>, /Users/runner/work/sentry-dotnet/sentry-dotnet/integration-test/cli.Tests.ps1:153
```

We no longer need to run this build target manually as part of the environment setup.